rosflight/rosflight_ros_pkgs

rosflight/include/rosflight/rosflight_io.h
rosflight/src/rosflight_io.cpp
rosflight_sim/include/ROSflight_sil.h
rosflight_sim/include/SIL_board.h
rosflight_sim/include/fixedwing_forces_and_moments.h
rosflight_sim/include/mav_forces_and_moments.h
rosflight_sim/include/multirotor_forces_and_moments.h
rosflight_sim/src/ROSflight_sil.cpp
rosflight_sim/src/SIL_board.cpp
rosflight_sim/src/fixedwing_forces_and_moments.cpp
rosflight_sim/src/multirotor_forces_and_moments.cpp

I pulled all gazebo dependencies out of the dynamics, and moved to using Eigen instead of math::Vector3.   I also added more realistic sensor models for all sensors, and cleaned up a little bit how the wind works.

some cleanup and review

---

rosflight_sim/params/fixedwing.yaml

Note: Trim conditions are also included at the bottom of the file, where they weren't there for the previous fixedwing params. Are these necessary here? Or should they be removed?

Changed fixedwing params to match myTwinDream

---

rosflight/CMakeLists.txt
rosflight/include/rosflight/mag_cal.h
rosflight/src/mag_cal.cpp
rosflight/src/mag_cal_node.cpp

Took Jerel's mag calibration and put it in a node similar to the imu node Dan wrote. I tested the calibration using rviz and it looks good.

Mag calibration

---

rosflight_sim/src/fixedwing_forces_and_moments.cpp

@superjax I think I found at least one of the bugs. I don't have a very good setup to test the fw sil, so can you test this and tell me what you think?

found this little bug, seems to be working a little better

---

rosflight/include/rosflight/mavrosflight/time_manager.h
rosflight/src/mavrosflight/time_manager.cpp

Pull Request Guidelines
All pull requests should adhere to the [style guide](http://docs.rosflight.org/en/developer_docs/developer-guide/style_guide/) and should pass the ROS prerelease tests.
Any pull request not adhering to these guidelines will be rejected.

Timing fix for time retrieval, made microsecond functions 64 bit

---

rosflight/include/rosflight/mavrosflight/param_manager.h
rosflight/src/mavrosflight/param_manager.cpp

Added timer to throttle rate at which params are sent

---

README.md
prerelease_test.sh
rosflight_msgs/package.xml
rosflight_pkgs/package.xml

Small tweaks

---

rosflight/CHANGELOG.rst
rosflight_firmware/CHANGELOG.rst
rosflight_msgs/CHANGELOG.rst
rosflight_pkgs/CHANGELOG.rst
rosflight_sim/CHANGELOG.rst
rosflight_utils/CHANGELOG.rst

Pull Request Guidelines
All pull requests should adhere to the [style guide](http://docs.rosflight.org/en/developer_docs/developer-guide/style_guide/) and should pass the ROS prerelease tests.
Any pull request not adhering to these guidelines will be rejected.

Updated changelogs

---

prerelease_test.sh

Added lunar distro to prerelease test script

---

rosflight_utils/CMakeLists.txt
rosflight_utils/package.xml

Fixes build error introduced by #84

Added missing visualization_msgs dependency for rosflight_utils

---

rosflight/include/rosflight/rosflight_io.h
rosflight/src/rosflight_io.cpp

Goes with the `attitude_correction` branch of the firmware

Attitude correction

---

rosflight_utils/src/rc_joy

Cleans up the method for configuring different controller types. Has been tested some with all three controllers and seems to work. Some more verification might be valuable though.
Supersedes #80

Cleaned up rc_joy node

---

rosflight_firmware/include/rosflight_firmware/udp_board.h
rosflight_firmware/src/udp_board.cpp
rosflight_sim/include/rosflight_sim/sil_board.h
rosflight_sim/src/sil_board.cpp

SIL: properly override abstract Board methods

---

rosflight_sim/include/rosflight_sim/sil_board.h

Pull Request Guidelines
All pull requests should adhere to the [style guide](http://docs.rosflight.org/en/developer_docs/developer-guide/style_guide/) and should pass the ROS prerelease tests.
Any pull request not adhering to these guidelines will be rejected.

fixed build issues

---

rosflight_sim/src/sil_board.cpp

fixed SIL problem

---

rosflight/include/rosflight/rosflight_io.h
rosflight/src/rosflight_io.cpp

update firmware to master, throttle back receieved parameters error

---

rosflight_sim/include/rosflight_sim/sil_board.h
rosflight_sim/src/multirotor_forces_and_moments.cpp
rosflight_sim/src/rosflight_sil.cpp
rosflight_sim/src/sil_board.cpp

Issue62 simulate drag error

---

rosflight_sim/include/rosflight_sim/sil_board.h
rosflight_sim/src/sil_board.cpp

Supports @dpkoch's latest changes to backup SRAM in sim.
Now ready.

Backup sram sim

---

.travis.yml

This enables CI testing for melodic

Enable CI for melodic

---

rosflight/src/rosflight_io.cpp

This fixes the regression introduced by #143

fix build issue after removing ALTITUDE command type

---

rosflight_sim/include/rosflight_sim/sil_board.hpp
rosflight_sim/src/sil_board.cpp

Updated the mag and gnss simulations to be Gauss-Markov processes. Added reasonable default values.

Sensor gauss markov process update

---

rosflight_io/src/rosflight_io.cpp
rosflight_msgs/msg/GNSS.msg
rosflight_sim/params/multirotor_firmware.yaml
rosflight_sim/simulators/standalone_sim/src/standalone_dynamics.cpp
rosflight_sim/simulators/standalone_sim/src/standalone_sensors.cpp
rosflight_sim/src/dynamics_interface.cpp
rosflight_sim/src/sil_board.cpp

Removed redundant information from gnss message in mavlink, so updating the `rosflight_io` and `standalone_sensors` and the GNSS.msg was necessary.

Remove gnss redundant information

---

.gitmodules
rosflight_io/CMakeLists.txt
rosflight_io/include/rosflight_io/mavrosflight/mavlink_bridge.hpp
rosflight_io/include/rosflight_io/mavrosflight/mavlink_comm.hpp
rosflight_msgs/msg/GNSS.msg
rosflight_sim/CMakeLists.txt
rosflight_sim/include/rosflight_sim/sil_board.hpp
rosflight_sim/include/rosflight_sim/sil_board_ros.hpp
rosflight_sim/src/sil_board.cpp
rosflight_sim/src/sil_board_ros.cpp

This PR fixes breaking changes caused by the board.h interface file in the firmware. The location of the `rosflight_firmware` submodule has also changed so that both `rosflight_io` and `rosflight_sim` can access the files without duplicate submodules.

Updates from firmware board.h

---

rosflight_sim/params/rotor_positional_config.yaml
rosflight_sim/scripts/calc_moments_of_interia.py

Added script to calculate moments of inertia based on the position config file. Found in rosflight_sim/params and rosflight_sim/scripts

Added script to calculate moments of inertia
