- rosflight_utils/src/libnmea_navsat_driver/parser.py
This just adds the most recent commit from the [nmea_navsat_driver](https://github.com/ros-drivers/nmea_navsat_driver/commit/904ea247aa0c5305facf71811defc846394b28d3) which adds support for GLONASS nmea sentences (like those that the ublox m8 produces).  How it is now I think works fine, but is less robust.
I've tested the changes with an m8 GPS and it works as expected
> parse GLONASS nmea sentences

- rosflight/include/rosflight/mavrosflight/mavlink_comm.h
This allows rosflight to build under Arch linux. (Other platforms are probably affected as well.) cerr was being used in mavlink_comm.cpp without including iostream.
> add includes for std libs to fix build

- README.md
- rosflight_utils/CMakeLists.txt
- rosflight_utils/include/rosflight_utils/viz.h
- rosflight_utils/launch/viz_attitude.launch
- rosflight_utils/rviz/viz_att.rviz
- rosflight_utils/src/viz.cpp
Cleaned up the magnetometer visualization code. Renamed `viz_mag` to `viz` and folded in a republisher from `rosflight_msgs/Attitude` to `geometry_msgs/PoseStamped` so the attitude can be viewed in rviz.
The fact that the attitude portion of the viz is merely a republisher for mismatching message types makes me wonder if `rosflight_io` should be publishing on the tf tree? (see https://github.com/rosflight/rosflight/issues/33) Or maybe you don't think this viz code belongs in this repo? Visualization of attitude just seems like a natural thing to do to test ROSflight out-of-the-box.
> visualization tools

- rosflight_firmware/CMakeLists.txt
When running SIL `GIT_VERSION_HASH` and `GIT_VERSION_STRING` were not set. Now the firmware version shows up in output of `rosflight_io`.
PS, do you see anything wrong with updating the [`rosflight_firmware/firmware`](https://github.com/rosflight/rosflight/tree/master/rosflight_firmware) submodule to master? Or at least 1.2.0?
> Set git defines for firmware version

- rosflight_msgs/msg/GNSS.msg
The fix type field in the GNSS message is taken from the UBX protocol. This currently requires users to refer to the UBX protocol to understand this field. This request adds enum values to the message, which will allow for easier and cleaner programming. The message itself is unchanged, so this will not break compatibility. The enum fields were taken from UBX read.
> Add enum values to the GNSS message, for readability

- rosflight/src/rosflight_io.cpp
Changes the default port to /dev/ttyACM0, because the revo uses that, and nazes are deprecated.
> Change default port to /dev/ttyACM0 to match the revo

- rosflight/src/rosflight_io.cpp
This was causing "Got unhandled mavlink message ID 199" debug messages to be
printed erroneously.
> Added missing break statement

- rosflight_firmware/CMakeLists.txt
This should get around it for now by setting the `GIT_VERSION_HASH` and `GIT_VERSION_STRING` CMake variables to default values of `0` and `undefined` when the git commands (silently) fail
> Hotfix for buildfarm failure with git version commands

- rosflight/CMakeLists.txt
- rosflight/include/rosflight/logger_ros.h
- rosflight/include/rosflight/mavrosflight/default_logger.h
- rosflight/include/rosflight/mavrosflight/logger_adapter.h
- rosflight/include/rosflight/mavrosflight/logger_interface.h
- rosflight/include/rosflight/mavrosflight/mavrosflight.h
- rosflight/include/rosflight/mavrosflight/param_manager.h
- rosflight/include/rosflight/mavrosflight/time_manager.h
- rosflight/include/rosflight/ros_logger.h
- rosflight/include/rosflight/rosflight_io.h
- rosflight/src/mavrosflight/mavrosflight.cpp
- rosflight/src/mavrosflight/param_manager.cpp
- rosflight/src/mavrosflight/time_manager.cpp
- rosflight/src/rosflight_io.cpp
Part of #131.
Abstract the use of ROS loggers out of mavrosflight. 
Because you need to declare the type of a template class in the file where it is implemented, I added the USE_ROS and STANDALONE compiler macros which are checked in `mavrosflight.cpp`, `time_manager.cpp`, and `param_manager.cpp`. Not sure if this is the cleanest/best option.
Currently there is a `warning: format not a string literal and no format arguments` when this is built. This is because we are passing the format string into the logger as a variable. I think typically the compiler can trace `const char*` and figure out if there is an issue, but I think there is something in what I am doing that makes it unable to track down the use of the format string. If you have any suggestions on how to get rid of that warning, …
> Mavrosflight logger abstraction

- rosflight/include/rosflight/mavrosflight/interface_adapter.h
- rosflight/include/rosflight/mavrosflight/mavrosflight.h
- rosflight/include/rosflight/mavrosflight/time_interface.h
- rosflight/include/rosflight/mavrosflight/time_manager.h
- rosflight/include/rosflight/ros_time.h
- rosflight/include/rosflight/ros_time_interface.h
- rosflight/include/rosflight/rosflight_io.h
- rosflight/src/mavrosflight/mavrosflight.cpp
- rosflight/src/mavrosflight/param_manager.cpp
- rosflight/src/mavrosflight/time_manager.cpp
- rosflight/src/rosflight_io.cpp
Abstract the use of `rostime` from `mavrosflight` and change all time types to `std::chrono` types.
> Mavrosflight rostime abstraction

- .clang-format
- .github/workflows/clang-format.yml
- README.md
- fix_code_style.sh
- rosflight_io/include/rosflight_io/mavrosflight/mavlink_comm.hpp
- rosflight_io/include/rosflight_io/mavrosflight/mavlink_serial.hpp
- rosflight_io/include/rosflight_io/mavrosflight/mavlink_udp.hpp
- rosflight_io/include/rosflight_io/mavrosflight/serial_exception.hpp
- rosflight_io/src/mag_cal.cpp
- rosflight_io/src/mavrosflight/mavlink_comm.cpp
- rosflight_io/src/mavrosflight/mavlink_serial.cpp
- rosflight_io/src/mavrosflight/mavlink_udp.cpp
- rosflight_io/src/mavrosflight/mavrosflight.cpp
- rosflight_io/src/mavrosflight/param.cpp
- rosflight_io/src/mavrosflight/param_manager.cpp
- rosflight_io/src/mavrosflight/time_manager.cpp
- rosflight_io/src/rosflight_io.cpp
- rosflight_sim/include/rosflight_sim/sil_board.hpp
- rosflight_sim/include/rosflight_sim/udp_board.hpp
- rosflight_sim/src/fixedwing_forces_and_moments.cpp
- rosflight_sim/src/multirotor_forces_and_moments.cpp
- rosflight_sim/src/rosflight_sil.cpp
- rosflight_sim/src/sil_board.cpp
- rosflight_sim/src/udp_board.cpp
- rosflight_utils/src/viz.cpp
To help maintain a more consistent coding style, I've added an automatic clang-format compliance check, similar to what is found in the rosflight_firmware repo. I've also tweaked the clang-format file slightly, to improve the readability of class initialization lists.
> Linter for clang-format

- rosflight_sim/include/rosflight_sim/fixedwing_forces_and_moments.hpp
- rosflight_sim/include/rosflight_sim/sil_board.hpp
- rosflight_sim/params/anaconda_dynamics.yaml
- rosflight_sim/params/skyhunter_dynamics.yaml
- rosflight_sim/src/fixedwing_forces_and_moments.cpp
- rosflight_sim/src/sil_board.cpp
See associated issue.
The main point is the IMU sensor truth is now calculated in the same way as the UAV book. This improves consistency and accuracy.
Note the issues mentioned in the issue about friction and boot up.
> 25 imu sim update

- rosflight_sim/include/rosflight_sim/sil_board.hpp
- rosflight_sim/src/sil_board.cpp
There should be a way to enable consistent bias between boots. Though as it stands this is one line of code, I think a discussion is warranted, hence a PR. 
I think that this implementation is clunky since it requires a rebuild, but it is not something that would be changed often. Perhaps it is good enough? 
Another alternative is to find some way to pass it as a launch argument, but the route to do that is unclear to me.
Thoughts?
> Added consistent bias seed.

- rosflight_sim/CMakeLists.txt
- rosflight_sim/include/rosflight_sim/sil_board.hpp
- rosflight_sim/include/rosflight_sim/udp_board.hpp
- rosflight_sim/src/sil_board.cpp
- rosflight_sim/src/udp_board.cpp
The interface changes have been made. They assume that the sensors always have new data when queried. This hasn't caused strange behavior, and I believe that is how it was done before changing the interface. Just something that seems odd.
> 157 update board interface

- rosflight_rqt_plugins/package.xml
- rosflight_rqt_plugins/resources/param_tuning.ui
- rosflight_rqt_plugins/resources/param_tuning_example_config.yaml
- rosflight_rqt_plugins/src/param_tuning/param_tuning.py
- rosflight_rqt_plugins/src/param_tuning/param_tuning_client.py
- rosflight_rqt_plugins/src/param_tuning/param_tuning_plotter.py
- rosflight_rqt_plugins/src/param_tuning/param_tuning_widget.py
To improve the autopilot tuning experience, I added a plotter to the rqt-based tuning GUI. The plotter is dynamically populated with the same .yaml file that populates the parameter adjustment table. The plot correlates with the current tuning group, and if you switch which parameters you're tuning then the plot you're viewing also changes.
There are a few other things you can configure in the .yaml file, but that is explained in the example .yaml file.
> Rqt plotting gui

- rosflight_rqt_plugins/src/param_tuning/param_tuning.py
This pull request is to merge a bug fix that occurred when selecting a config file from the file explorer window. 
The other option is to pass the config file path in through command line arguments, and that was working. This change does not affect that functionality.
> ParamTuning RQT GUI config file loading

- rosflight_rqt_plugins/resources/param_tuning_multirotor.yaml
- rosflight_sim/include/rosflight_sim/sil_board.hpp
- rosflight_sim/launch/multirotor.launch.py
- rosflight_sim/params/multirotor_firmware.yaml
- rosflight_sim/src/sil_board.cpp
I changed the default gazebo world to the runway world so it was easier to see where the multirotor is. Also tweaked some of the gazebo launch arguments so it would spawn correctly. 
Also added updated definitions from `board.h` to the `sil_board` so we could use the latest commits of the firmware.
> Multirotor updates to sim packages and SIL board

- rosflight_sim/include/rosflight_sim/multirotor_forces_and_moments.hpp
- rosflight_sim/launch/multirotor_sim_io_joy.launch.py
- rosflight_sim/src/multirotor_forces_and_moments.cpp
- rosflight_sim/src/rc.py
- rosflight_sim/src/vimfly.py
This is ported from the roscopter repo in the BYU-Magicc org. It uses the vim keybindings for raw RC output. It can be jerky but it works to fly multi-rotors and fixedwings. You can't fly super well but it is good enough to allow for testing without the need for a controller.
It launches vimfly if the param is set to use it and if a controller is not detected. However, rc.py does not have a param file it uses, and I didn't want to add one for a single param. So to enable  VimFly you have to edit the default param value in the rc.py file. This is because the param has to be initialized at launch. If you have a better idea of how to implement this let me know!
> Vim Fly - A keyboard controller for the rosflight sim

- README.md
Having two instances of instructions for building and using rosflight is confusing and causes extra maintinence, so I removed the instructions already found on the website and added some extra links to point the user there.
> removed the building and usage instructions found on the website

- rosflight_io/include/rosflight_io/rosflight_io.hpp
- rosflight_io/src/rosflight_io.cpp
The saturation should happen in either the firmware or before the user sends commands to the firmware. This was also raising an issue as I was implementing controls that send passthrough commands to the mixer that are on a different scale than from [-1,1]. 
This pull request removes saturation from the `rosflight_io` node, making it the user's responsibility to saturate their input. Note that the mixer also does some saturation when composing motor and servo commands.
> removed saturation from the rosflight_io node

- rosflight_sim/CMakeLists.txt
- rosflight_sim/params/multirotor_firmware.yaml
- rosflight_sim/src/multirotor_forces_and_moments.cpp
Updated the propeller model for when the airspeed is opposite in direction from the body z axis (i.e. backwards). The implementation assumes the propeller performance when the airspeed flows backwards is the same as when airspeed is zero.
I also updated the firmware parameters and added the Eigen dependency to the `rosflight_sim` package, which were done in other branches. Both were needed for testing.
> Adjust propeller model roscopter sim

- rosflight_io/include/rosflight_io/rosflight_io.hpp
- rosflight_io/src/rosflight_io.cpp
- rosflight_sim/include/rosflight_sim/forces_and_moments_interface.hpp
- rosflight_sim/simulators/standalone_sim/CMakeLists.txt
- rosflight_sim/simulators/standalone_sim/include/fixedwing_forces_and_moments.hpp
- rosflight_sim/simulators/standalone_sim/include/multirotor_forces_and_moments.hpp
- rosflight_sim/simulators/standalone_sim/src/fixedwing_forces_and_moments.cpp
- rosflight_sim/simulators/standalone_sim/src/multirotor_forces_and_moments.cpp
- rosflight_sim/simulators/standalone_sim/src/standalone_dynamics.cpp
- rosflight_sim/src/forces_and_moments_interface.cpp
This PR enables other nodes to query `rosflight_io` for the current firmware parameters. 
This is needed because some implementations of the forces and moments need to know the mixer parameters to accurately unmix and compute the forces and moments. This is apparent when doing vtail mixing for a fixedwing, since our forces and moments equations assume the standard tail configuration. Thus, we either have to unmix the commands (to get back to servo commands that map to the standard tail configuration) or hard code a new forces and moments implementation. This PR allows the forces and moments node to query `rosflight_io` for the mixer parameters so it can use them internally.
Note that this also enables synching the parameters between the firmware and other nodes.
`rosflight_io`:
- Added …
> 195 plane acts erratically under computer or manual control    v tail mixer issues in the simulation

- rosflight_io/include/rosflight_io/rosflight_io.hpp
- rosflight_io/src/rosflight_io.cpp
- rosflight_sim/simulators/standalone_sim/launch/multirotor_standalone.launch.py
This PR exposes firmware gains to the ROS2 parameter interface for the ROSflight_io node. This makes it really easy to change the parameters, useful for parameter tuning. Before, we had to change the gains and other parameters via service call.
Specifically, I added a std::set that holds a list of user-defined parameters that we care about exposing. Right now, it is only controller gains. Gains can still be edited through the `rosflight_msgs/srv/ParamSet` service call, and will automatically be synced with the ROS2 gains.
Also note that on startup, once all the params have been received by `rosflight_io`, it loads the convenience parameters to the ROS2 parameters, handling the case where the parameters were saved to the firmware memory.
> Expose firmware control gains to ROS2 parameter interface
